os: linux
language: generic

branches:
  only:
  - master

install:
  - nvm install 8

script:
  - set -e
  - ./scripts/travis-fold "npm install"
  - ./scripts/travis-fold "npm run build"
  - ./scripts/travis-fold "npm run test"
  - ./scripts/travis-fold "npm run release"
  - set +e

after_script:
  - echo "BUILD FINISHED"

notifications:
  email: false
  slack:
    secure: GSabiSFHTa8TwsgcHJespMYHPZEDvCSh4dfVSfeVAHyPVoG2k5IwwHqE3cqY66ltey7qcTjiiv9aQ1uh5ESjbgD4vEquW2m5s16UywqvWXzCu1pbUattnNvDdP0FYQH4y3KSR7RLM+knlcHGth8/e+oSFhp7eNl9h0+UBznxI2pPhl6TKcjFwj2amEWA5FV2p4AmQ3+mjkN4t29b39TIniO2JIyLA2B5bNkjWEnaGVLfBtH/LR5inIGTUvWQ96/mhJsmYAdgovqfuglTdgZwoN/anDGo2EFNcTciUAJ70GBVpubGQIlbfn71H9LgJcGjxRRVYs67O92fTh1dYW4hk5Z7i+376CyGlp5KPia/IY6JJ8kJDALCZ5oaffZHdte5n/obTJ6LXYz8MLpbG8wR01sCz/vFm4WHwDMzRaS6yq97I3Pd+q2OU553TO0jqEVafSBmgBTcYwU1TW0hWQOMq3wiqvdayVNzcO/y5kIg87ooJ5C/f6PIKyTeL1wZsTBzOwdffMJ0Q3Hgku+ELhpl6OSBUjFRwBPXdeVKRbozjOc2nKb7ml7A/SC8ielthdzUfEEHJahMWil1FJOmYOtzAHnWG69fky/cBjf+RoKBuQOZm6LIeoXbAvOzP0a/p7tSGFq2K6+hPoo3CvTxc+PELIdLLyrkg6gon0GcqIiuzn0=
